[package]
name = "botan-src"
version = "0.31200.0"
authors = ["Jack Lloyd <jack@randombit.net>", "Rodolphe Breard <rodolphe@what.tf>"]
description = "Sources of Botan cryptography library"
license = "MIT"
edition = "2024"
homepage = "https://botan.randombit.net/"
repository = "https://github.com/randombit/botan-rs"
readme = "README.md"
categories = ["cryptography"]
rust-version = "1.85"
build = "build.rs"

include = [
    "Cargo.toml",
    "README.md",
    "build.rs",
    "release.toml",
    "src/**/*.rs",
    "examples/**/*.rs",
    "scripts/fetch.py",
    "vendor/Botan-*.tar.xz",
]

[dependencies]
lzma-rs = { version = "0.3", default-features = false }
sha2 = { version = "0.10", default-features = false }
tar = { version = "0.4", default-features = false }

[[example]]
name = "build"
path = "examples/build.rs"
